### ISSUE TITLE
h850: Unable to create dtb.img

### ISSUE THREAD

**Issue by h2o64** [jcadduono/android_kernel_lge_msm8996-caf#1]
Hello !
I tried building your kernel manually (no modifications done) but it keeps failing when it comes to getting the dtb.img
`make[1]: Leaving directory '/home/louis/Dev/LABS/G5/nethunter_kernel_g5/build'
make: Leaving directory '/home/louis/Dev/LABS/G5/nethunter_kernel_g5'
Generating dtb.img...
DTB combiner:
  Input directory: '/home/louis/Dev/LABS/G5/nethunter_kernel_g5/build/arch/arm64/boot/'
  Output file: '/home/louis/Dev/LABS/G5/nethunter_kernel_g5/build/arch/arm64/boot/dtb.img'
Searching subdir: /home/louis/Dev/LABS/G5/nethunter_kernel_g5/build/arch/arm64/boot/dts/ ... 
Searching subdir: /home/louis/Dev/LABS/G5/nethunter_kernel_g5/build/arch/arm64/boot/dts/lge/ ... 
Found file: msm8996-h1_global_rev-b_v3-pmi8996.dtb ... 
Version:1
... skip, incorrect 'qcom,msm-id = <' format
skip, failed to scan for 'qcom,msm-id = <' tag
Found file: msm8996-h1_global_rev-a_v3-pmi8996.dtb ... 
Version:1
... skip, incorrect 'qcom,msm-id = <' format
skip, failed to scan for 'qcom,msm-id = <' tag
Searching subdir: /home/louis/Dev/LABS/G5/nethunter_kernel_g5/build/arch/arm64/boot/dts/arm/ ... 
Found file: msm8996-h1_global_evb-a_v3.0-pmi8996.dtb ... 
Version:1
... skip, incorrect 'qcom,msm-id = <' format
skip, failed to scan for 'qcom,msm-id = <' tag
Found file: msm8996-h1_global_evb-a_v3-pmi8996.dtb ... 
Version:1
... skip, incorrect 'qcom,msm-id = <' format
skip, failed to scan for 'qcom,msm-id = <' tag
Found file: msm8996-h1_global_rev-1.0_v3-pmi8996.dtb ... 
Version:1
... skip, incorrect 'qcom,msm-id = <' format
skip, failed to scan for 'qcom,msm-id = <' tag
Searching subdir: /home/louis/Dev/LABS/G5/nethunter_kernel_g5/build/arch/arm64/boot/dts/apm/ ... 
Searching subdir: /home/louis/Dev/LABS/G5/nethunter_kernel_g5/build/arch/arm64/boot/dts/cavium/ ... 
=> Found 0 unique DTB(s)
Finished building nethunter-h850-1.1!
Moving kernel Image.gz and dtb.img to /home/louis/build/kali-nethunter/nethunter-installer/kernels/marshmallow/h850/...
mv: impossible d'évaluer «/home/louis/Dev/LABS/G5/nethunter_kernel_g5/build/arch/arm64/boot/dtb.img»: Aucun fichier ou dossier de ce type
Failed to build h850! Aborting...
`

**Comment by jcadduono** [comment]
Yeah I noticed this happens on some computers and I'm not sure what the
cause is yet, seems to be related to dtbTool reading files ...need to
change the read code a bit I guess.

**Comment by h2o64** [comment]
Well the problem is : by using "KDIR" to output the sources, you loose all your relative paths in dtbs. And the h1*.dts files depends on files in "../qcom" which define the "qcom,msm-id"

**Comment by jcadduono** [comment]
Uh no? The error you are getting is in the last step which is just
concatenation into an indexed dtb.img. nothing is missing. The dtbTool just
can't read the dtb files (which are properly generated, I verified them
with hashes when someone else had this issue)

**Comment by h2o64** [comment]
"Found 0 dtbs"  doesn't that mean it didn't get generated?

**Comment by jcadduono** [comment]
Found 0 dtbs means that dtb.img did not get generated. The previous errors of being unable to find msm-id tags is the issue. The dtb files are being generated fine, but the dtbTool that reads them and makes them into a dtb.img is incorrectly reading the .dtb files on some operating systems. I need to fix the .dtb -> dtb.img converter.

**Comment by shminer** [comment]
sudo apt install device-tree-compiler

**Comment by jcadduono** [comment]
well, this one's officially closed. i fixed the bug in qualcomm's dtbtool and made other various fixes and error checking. -p is now -d and is a direct path to dtc tool in kernel source tree build dir as well, so no need to install device-tree-compiler either
